version: '3.1'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db_password"
       MYSQL_USER_FILE: "/run/secrets/db_user"
       MYSQL_PASSWORD_FILE: "/run/secrets/db_password"
       MYSQL_DATABASE: wordpress
     secrets:
      - db_user
      - db_password

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     secrets:
      - db_user
      - db_password
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER_FILE: "/run/secrets/db_user"
       WORDPRESS_DB_PASSWORD_FILE: "/run/secrets/db_password"

volumes:
    db_data:

secrets:
  db_password:
    external: true
  db_user:
    file: ./db_user.txt
